function textareaResize(a,b){b&&("absolute"==a.style.position?(a.style.position="",a.style.width="",a.parentNode.style.height="",a.style.height="",a.parentNode.style.verticalAlign="middle"):(a.parentNode.style.height=a.parentNode.offsetHeight+"px",a.style.width=phpcom.isIE6?"650px":"75%",a.style.position="absolute",a.parentNode.style.verticalAlign="top"))}function toRefresh(a){window.location.reload()}function toRedirect(a){window.location.replace(a)}
function formdown(){return 13==event.keyCode?!1:!0}function changeRunSystem(a){if(!a)return!1;var b=$("runsystemtext"),c=b.value;""==c?b.value=a:-1==c.indexOf(a)&&(b.value+=", "+a);b.focus();return!1}function make_authkey(a,b){var c="",d=$(a);b=isUndefined(b)?32:b;if(d&&""==d.value){for(var f=0;f<b;f++)c+="0123456789QWERTYUIOPASDFGHJKLZXCVBNMqwertyuioplkjhgfdsazxcvbnm".charAt(Math.ceil(1E8*Math.random())%62);d.value=c}}
function checkAll(a,b,c,d){d=d?d:"chkall";for(var f=0;f<b.elements.length;f++){var e=b.elements[f];"option"==a&&"radio"==e.type&&e.value==c&&!0!=e.disabled?e.checked=!0:"value"==a&&"checkbox"==e.type&&e.getAttribute("chkvalue")==c?e.checked=b.elements[d].checked:"prefix"==a&&e.name&&e.name!=d&&(!c||c&&e.name.match(c))&&(e.checked=b.elements[d].checked)}}function toggleFormTarget(a,b){b=undef(b,"_framethread");isUndefined(a.form.target)||(a.form.target="_blank"==a.form.target?b:"_blank")}
function alterStyle(a,b){b=isUndefined(b)?"li":b;var c=phpcom.isIE,d,f,e,g,h;g=0;f=a.getElementsByTagName(b);for(e=0;e<f.length;e++)f[e].onclick=function(a){h=c?event.srcElement.tagName:a.target.tagName;if(!g&&(g=1,d=this.getElementsByTagName("input")[0],"checkbox"==d.getAttribute("type")||"radio"==d.getAttribute("type"))){if("radio"==d.getAttribute("type")){var e;a=this.parentNode.getElementsByTagName(b);for(e=0;e<a.length;e++)a[e].className=""}(c||"INPUT"!=h&&d.onclick)&&d.click();"checked"!=this.className?
(this.className="checked",d.checked=!0):(this.className="",d.checked=!1)}},f[e].onmouseup=function(a){g=0}}function toggle_display(a){var b=$("groupbody_"+a);null!=b&&("none"==b.style.display?(b.style.display="",$("toggle_"+a).className="toggle hide-icon"):(b.style.display="none",$("toggle_"+a).className="toggle show-icon"))}
function toggle_all(a){for(var b=$("adminform").getElementsByTagName("tbody"),c=0;c<b.length;c++){var d=/^groupbody_(\d+)$/.exec(b[c].id);null!=d&&("hide"==a?(b[c].style.display="none",$("toggle_"+d[1]).className="toggle show-icon"):(b[c].style.display="",$("toggle_"+d[1]).className="toggle hide-icon"))}}function toggleDisplay(a,b){"hide"==b?$(a).style.display="none":$(a).style.display=""}function hideDisplay(a){$(a).style.display=""==$(a).style.display?"none":""}
function showDescrLength(a){a=$(a);null!=a?alert("\u5f53\u524d\u63cf\u8ff0\u957f\u5ea6\u4e3a "+a.value.length+" \u5b57\u8282\uff01"):alert("\u5f53\u524d\u63cf\u8ff0\u957f\u5ea6\u4e3a 0 \u5b57\u8282\uff01")}function changeSelectColor(a){var b=a.options[a.selectedIndex].text;0==a.value?(a.style.color="black",a.style.backgroundColor="white"):(a.style.color=b,a.style.backgroundColor=b)}
function toggle_highlightstyle(a,b,c){c=isUndefined(c)?"highlight_style":c;c=$(c);var d=parseInt(c.value);a.className.match(/ btncnt/i)?(4>d?c.value=0:7==d?c.value=7-b:(b=d-b-1,c.value=0>b?0:b),a.className=a.className.replace(/ btncnt/,"")):(0==d?c.value=b:(b=d+b+1,c.value=7<b?7:b),a.className+=" btncnt")}
function toggle_anchor(a,b){for(var c=$("nav_tabs").getElementsByTagName("li"),d=0;d<c.length;d++)"nav_"==c[d].id.substr(0,4)&&c[d].id!=a.id&&$(c[d].id.substr(4))&&(c[d].className="",$(c[d].id.substr(4)).style.display="none",$(c[d].id.substr(4)+"_tips")&&($(c[d].id.substr(4)+"_tips").style.display="none"));a.className="active";currentAnchor=a.id.substr(4);$(currentAnchor).style.display="";$(currentAnchor+"_tips")&&($(currentAnchor+"_tips").style.display="");$(b)&&($(b).innerHTML=a.title)}
function toggle_tabstrip(a){$("btn_"+a)}function show_style(){return openDialog("static/admin/setstyle.htm","window","\u8bbe\u7f6e\u98ce\u683c",290,240,0)}function cancel_style(){$("title_style").value="";$("demo_style").innerHTML='<span style="background:#ffffff;font-size:12px">\u8bbe\u7f6e\u6807\u9898\u6837\u5f0f ABC123</span>'}function previewColorValue(a){var b=$(a+"_v").value;$(a).style.backgroundColor=b}
function activeTabs(a){var b=parent.$("tabs");if(b&&(b=b.getElementsByTagName("a"))){for(var c=0,d=b.length;c<d;++c)""!==b[c].clssName&&(b[c].className="");if(a=parent.$("tabs_"+a))a.className="active",a.blur()}}
function addvoteOption(){if(300<=$("voteoptions").getElementsByTagName("span").length)return!1;var a=$("basevoteoption").cloneNode(!0);a.getElementsByTagName("a")[0].style.display="";var b=a.getElementsByTagName("input");b[0].value="";b[1].value="0";b[2].value="0";a.removeAttribute("id");$("voteoptions").insertBefore(a,$("addvote_button"))}function delvoteOption(a){a.parentNode.parentNode.removeChild(a.parentNode)}
function addPlayAddress(){var a=$("play_address_body").firstChild,b=a.getElementsByTagName("select")[0].selectedIndex,a=a.cloneNode(!0);a.getElementsByTagName("textarea")[0].value="";a.getElementsByTagName("textarea")[0].name="addressnew[]";a.getElementsByTagName("select")[0].selectedIndex=b;a.getElementsByTagName("select")[0].name="playernew[]";a.getElementsByTagName("input")[0]&&(a.getElementsByTagName("input")[0].value="",a.getElementsByTagName("input")[0].name="captionnew[]");$("play_address_add").insertBefore(a,
null)}function insert_tags(){return openDialog("?m=tags&action=insert","tags","\u63d2\u5165Tags",820,460)}function showTopicMenu(a,b){var c=a.id,d=ajaxObject(),f=(new Date).getTime();b+=0<=b.indexOf("?")?"&t="+f:"?t="+f;b=b.replace(/\&inajax\=1/g,"")+"&inajax=1";d.get(b,function(a){$(c+"_menu").innerHTML=a;showMenu({ctrlid:c})})}
function threadModify(a,b){var c=0;b=b?b:"";for(var d=0;d<$("adminform").elements.length;d++)if($("adminform").elements[d].name.match("delete")&&$("adminform").elements[d].checked){c=1;break}c?($("adminform").channelid.value=a,$("adminform").action.value=b,styleWindow("?m=ajax_setstyle","floatctrl_drag")):alert("\u8bf7\u9009\u62e9\u9700\u8981\u64cd\u4f5c\u7684\u4e3b\u9898\uff01")}var rowtypedata=["&nbsp;",'<input name="newquestion[]" type="text" size="50" class="input">','<input name="newanswer[]" type="text" size="35" class="input">'];
function addrow(a,b){var c=a.parentNode.parentNode.parentNode.parentNode.parentNode.insertRow(a.parentNode.parentNode.parentNode.rowIndex),d=rowtypedata;c.className="tr-1";for(var f=0;f<=d.length-1;f++){var e=c.insertCell(f),g=d[f];e.className="tablerow1";e.innerHTML=g}}function deleterow(a){a.parentNode.parentNode.parentNode.parentNode.parentNode.deleteRow(a.parentNode.parentNode.parentNode.rowIndex)}
function openTopicWindow(){return openDialog("?m=special&action=select","special","\u9009\u62e9\u4e13\u9898",820,460)}function openQuickEdit(a,b){return openDialog("?m=soft&action=quickedit&tid="+a+"&chanid="+b,"quickedit","\u5feb\u901f\u7f16\u8f91",620,460)}function openThreadClassWindow(a){var b=$("catid").value;return openDialog("?m=category&action=select&chanid="+a+"&catid="+b,"threadclass","\u9009\u62e9\u5206\u7c7b",620,360)}
function selectThreadClass(a){a.size=a.options.length+1;a.style.position="absolute";a.style.height="";a.style.top="-2px";a.style.zIndex=999}function resetThreadClass(a){a.style.height="21px";a.style.position="";a.size=1}
function showSubcategory(a,b,c){var d=ajaxObject(),f=(new Date).getTime();a="apps/ajax.php?action=category&chanid="+c+"&rootid="+a.value;a+=0<=a.indexOf("?")?"&t="+f:"?t="+f;a=a.replace(/\&inajax\=1/g,"")+"&inajax=1";d.get(a,function(a){var c="";!isUndefined(b)&&$(b)?(c=parsescript(a),""!=c?($(b).innerHTML=c,$(b).style.display=""):($(b).innerHTML="",$(b).style.display="none")):""!=a&&parsescript(a)});return!1}
function initTopicSelect(a){if((a=parent.$(a))&&0<a.value.length){$("selectedstring").value=a.value;a=a.value.split(",");for(var b=0;b<a.length;b++){var c=$("checkbox_"+a[b]);c&&(c.checked=!0,c.parentNode.parentNode.className="item checked")}}}
function topicalAdd(a,b){var c=a.value,d=parent.$(b),f=$("selectedstring");if(d&&0<d.value.length){for(var e="",g=d.value.split(","),h=0;h<g.length;h++)""!=g[h]&&g[h]!=c&&(e+=g[h]+",");a.checked&&(e+=c);d.value=e;f.value=e}else a.checked?(d.value=c,f.value=c):(d.value="",f.value="");c=a.parentNode.parentNode;c.className="item"==c.className?"item checked":"item"}function simpleUploadWindow(a){}function imageUploadWindow(a){alert(a.value)}
function uploadingWindow(a,b,c,d,f){b=undef(b,"image");c=undef(c,0);d=undef(d,0);showWindow("apps/ajax.php?action=uploading&type="+a+"&dirname="+b+"&chanid="+c+"&tid="+d,"uploading")}function uploadingSubmit(a,b){if(a=$(a)){if(!isUndefined(b)&&$(b)){var c=b+"_extend";$(c)&&a.removeChild($(c));var d=$(b).cloneNode(!0);d.id=c;d.style.display="none";a.appendChild(d)}a.submit()}}
function uploadingImageDelete(a){!isUndefined(a)&&$(a)&&($(a).value="-1",alert("\u63d0\u4ea4\u5b8c\u6210\u540e\u7a0b\u5e8f\u5c06\u81ea\u52a8\u5220\u9664\u8be5\u56fe\u7247"))}
function loadUploadingWindow(a,b){var c=a.contentWindow.document.body.innerHTML;""!=c&&(c=(new Function("return "+c))(),c.status&&alert("\u4e0a\u4f20\u5931\u8d25"),isUndefined(b)?($("fileurl")&&($("fileurl").value=c.attachment),$("tmpid")&&($("tmpid").value=c.attachid)):($(b)&&($(b).value=c.attachid),$(b+"_file")&&($(b+"_file").value=c.attachment)))};
