function bbeditor_showimgmenu(a){var c=$(a+"_image_param_1").value,b=parseInt($(a+"_image_param_2").value),d=parseInt($(a+"_image_param_3").value),e="";if(b||d)e="="+b+","+d;bbeditor_insertunit(a,"[img"+e+"]"+c,"[/img]",null,1);$(a+"_image_param_1").value="";hideMenu()}
function bbeditor_insertunit(a,c,b,d,e){$(a+"message")&&$(a+"message").focus();b=isUndefined(b)?"":b;d=isUndefined(b)?0:d;e=isUndefined(e)?1:e;startlen=strlen(c);endlen=strlen(b);if(isUndefined($(a+"message").selectionStart))if(document.selection&&document.selection.createRange){var f=document.selection.createRange();!f.text.length&&$(a+"message").sel&&(f=$(a+"message").sel,$(a+"message").sel=null);e?(""!=b&&(c=c+f.text+b),f.text=c.replace(/\r?\n/g,"\r\n"),d||(f.moveStart("character",-endlen),f.moveEnd("character",
-endlen)),f.select()):f.text=c+b}else $(a+"message").value+=c;else e?(e=$(a+"message").selectionStart+0,""!=b&&(c=c+$(a+"message").value.substring($(a+"message").selectionStart,$(a+"message").selectionEnd)+b),$(a+"message").value=$(a+"message").value.substr(0,$(a+"message").selectionStart)+c+$(a+"message").value.substr($(a+"message").selectionEnd),d||($(a+"message").selectionStart=e+strlen(c)-endlen,$(a+"message").selectionEnd=e+strlen(c)-endlen)):(c+=b,$(a+"message").value=$(a+"message").value.substr(0,
$(a+"message").selectionStart)+c+$(a+"message").value.substr($(a+"message").selectionEnd));hideMenu(2);phpcom.isIE&&phpcom.endEvent()}function bbeditor_ctlent(a,c){(a.ctrlKey&&13==a.keyCode||a.altKey&&83==a.keyCode)&&eval(c)}
function loadimgsize(a,c,b){var c=!c?editorid:c,d={},b=!b?"_image":b;d.img=new Image;d.img.src=a;d.loadCheck=function(){d.img.complete?($(c+b+"_param_2").value=d.img.width?d.img.width:"",$(c+b+"_param_3").value=d.img.height?d.img.height:""):setTimeout(function(){d.loadCheck()},100)};d.loadCheck()}
function bbeditor_menu(a,c){var b=!1;isUndefined($(a+"message").selectionStart)?document.selection&&document.selection.createRange&&($(a+"message").focus(),b=document.selection.createRange(),$(a+"message").sel=b,b=b.text?!0:!1):b=$(a+"message").selectionEnd-$(a+"message").selectionStart;if(b)bbeditor_insertunit(a,"["+c+"]","[/"+c+"]");else{var b=a+c,d=b+"_menu";if(!$(d)){switch(c){case "url":str='\u8bf7\u8f93\u5165\u94fe\u63a5\u5730\u5740:<br /><input type="text" id="'+b+'_param_1" sautocomplete="off" style="width: 98%" value="" class="input" /><br />\u8bf7\u8f93\u5165\u94fe\u63a5\u6587\u5b57:<br /><input type="text" id="'+
b+'_param_2" style="width: 98%" value="" class="input" />';submitstr="$('"+b+"_param_2').value !== '' ? bbeditor_insertunit('"+a+"', '[url='+$('"+b+"_param_1').value+']'+$('"+b+"_param_2').value, '[/url]', null, 1) : bbeditor_insertunit('"+a+"', '[url]'+$('"+b+"_param_1').value, '[/url]', null, 1);hideMenu();";break;case "code":case "quote":str={quote:"\u8bf7\u8f93\u5165\u8981\u63d2\u5165\u7684\u5f15\u7528",code:"\u8bf7\u8f93\u5165\u8981\u63d2\u5165\u7684\u4ee3\u7801"}[c]+':<br /><textarea id="'+
b+'_param_1" style="width: 98%" cols="50" rows="5" class="txtarea"></textarea>';submitstr="bbeditor_insertunit('"+a+"', '["+c+"]'+$('"+b+"_param_1').value, '[/"+c+"]', null, 1);hideMenu();";break;case "img":str='\u8bf7\u8f93\u5165\u56fe\u7247\u5730\u5740:<br /><input type="text" id="'+b+'_param_1" style="width: 98%" value="" class="input" onchange="loadimgsize(this.value, \''+a+"','"+c+'\')" /><p style="margin-top:10px">\u5bbd(\u53ef\u9009): <input type="text" id="'+b+'_param_2" style="width: 15%" value="" class="input" /> &nbsp;\u9ad8(\u53ef\u9009): <input type="text" id="'+
b+'_param_3" style="width: 15%" value="" class="input" /></p>',submitstr="bbeditor_insertunit('"+a+"', '[img' + ($('"+b+"_param_2').value !== '' && $('"+b+"_param_3').value !== '' ? '='+$('"+b+"_param_2').value+','+$('"+b+"_param_3').value : '')+']'+$('"+b+"_param_1').value, '[/img]', null, 1);hideMenu();"}var e=document.createElement("div");e.id=d;e.style.display="none";e.className="pwrap";e.style.width="270px";try{document.body.insertBefore(e,null)}catch(f){}e.innerHTML='<span class="y"><a onclick="hideMenu()" class="pclose" href="javascript:;">\u5173\u95ed</a></span><div class="p_opt cl"><form onsubmit="'+
submitstr+';return false;" autocomplete="off"><div>'+str+'</div><div style="margin-top:10px"><button type="submit" id="'+b+'_submit" class="btn"><strong>\u63d0\u4ea4</strong></button> &nbsp; <button type="button" onClick="hideMenu()" class="btn b3"><em>\u53d6\u6d88</em></button></div></form></div>'}showMenu({ctrlid:b,evt:"click",duration:3,cache:0,drag:1})}}
function showColorBox(a,c,b,d){d=!d?"color":"backcolor";if(!$(a+"_menu")){var e=document.createElement("div");e.id=a+"_menu";e.className="pwrap colorbox";e.unselectable=!0;e.style.display="none";for(var f="Black Sienna DarkOliveGreen DarkGreen DarkSlateBlue Navy Indigo DarkSlateGray DarkRed DarkOrange Olive Green Teal Blue SlateGray DimGray Red SandyBrown YellowGreen SeaGreen MediumTurquoise RoyalBlue Purple Gray Magenta Orange Yellow Lime Cyan DeepSkyBlue DarkOrchid Silver Pink Wheat LemonChiffon PaleGreen PaleTurquoise LightBlue Plum White".split(" "),
i="\u9ed1\u8272 \u8d6d\u8272 \u6697\u6a44\u6984\u7eff\u8272 \u6697\u7eff\u8272 \u6697\u7070\u84dd\u8272 \u6d77\u519b\u8272 \u975b\u9752\u8272 \u58a8\u7eff\u8272 \u6697\u7ea2\u8272 \u6697\u6854\u9ec4\u8272 \u6a44\u6984\u8272 \u7eff\u8272 \u6c34\u9e2d\u8272 \u84dd\u8272 \u7070\u77f3\u8272 \u6697\u7070\u8272 \u7ea2\u8272 \u6c99\u8910\u8272 \u9ec4\u7eff\u8272 \u6d77\u7eff\u8272 \u95f4\u7eff\u5b9d\u77f3 \u7687\u5bb6\u84dd \u7d2b\u8272 \u7070\u8272 \u7ea2\u7d2b\u8272 \u6a59\u8272 \u9ec4\u8272 \u9178\u6a59\u8272 \u9752\u8272 \u6df1\u5929\u84dd\u8272 \u6697\u7d2b\u8272 \u94f6\u8272 \u7c89\u8272 \u6d45\u9ec4\u8272 \u67e0\u6aac\u7ef8\u8272 \u82cd\u7eff\u8272 \u82cd\u5b9d\u77f3\u7eff \u4eae\u84dd\u8272 \u6d0b\u674e\u8272 \u767d\u8272".split(" "),
h="",g=0;40>g;g++)h+='<input type="button" style="background-color: '+f[g]+'" onclick="bbeditor_insertunit(\''+b+"', '["+d+"="+f[g]+"]', '[/"+d+']\')" title="'+i[g]+'" />'+(39>g&&0==(g+1)%8?"<br />":"");e.innerHTML=h;try{document.body.insertBefore(e,null)}catch(j){}}showMenu({ctrlid:a,evt:"click",layer:c})};
