var agt=navigator.userAgent.toLowerCase(),is_ie=-1!=agt.indexOf("msie")&&-1==agt.indexOf("opera"),is_gecko="Gecko"==navigator.product,months="\u4e00\u6708 \u4e8c\u6708 \u4e09\u6708 \u56db\u6708 \u4e94\u6708 \u516d\u6708 \u4e03\u6708 \u516b\u6708 \u4e5d\u6708 \u5341\u6708 \u5341\u4e00\u6708 \u5341\u4e8c\u6708".split(" "),days=[31,28,31,30,31,30,31,31,30,31,30,31],weeks="\u65e5\u4e00\u4e8c\u4e09\u56db\u4e94\u516d".split(""),today,pX,pY,seltd,prebackground,precolor;
function getDays(c,d){return 1==c?0==d%4&&0!=d%100||0==d%400?29:28:days[c]}function getToday(c){var d=new Date;this.year=d.getFullYear();this.month=d.getMonth();this.day=d.getDate();1==c&&(this.hour=d.getHours(),this.minute=d.getMinutes(),10>this.hour&&(this.hour="0"+String(this.hour)),10>this.minute&&(this.minute="0"+String(this.minute)))}
function getSelectDay(c,d){c=c.split("-");var a=c[2].split(" ");1==d?(a=trim(a[1]).split(":"),a=new Date(parseFloat(c[0]),parseFloat(c[1])-1,parseFloat(c[2]),parseFloat(a[0]),parseFloat(a[1])),this.hour=a.getHours(),this.minute=a.getMinutes(),10>this.hour&&(this.hour="0"+String(this.hour)),10>this.minute&&(this.minute="0"+String(this.minute))):a=new Date(parseFloat(c[0]),parseFloat(c[1])-1,parseFloat(c[2]));this.year=a.getFullYear();this.month=a.getMonth();this.day=a.getDate()}
function showDays(){var c=$("Year"),d=$("Month"),c=parseInt(c.options[c.selectedIndex].value),a=new Date(c,d.selectedIndex,1),d=-1,c=a.getDay(),e=0;today.year==a.getFullYear()&&today.month==a.getMonth()&&(d=today.day);for(var b=$("Day"),a=getDays(a.getMonth(),a.getFullYear()),g=1;g<b.rows.length;g++)for(var f=0;f<b.rows[g].cells.length;f++){var h=b.rows[g].cells[f];f==c&&0==e&&(e=1);0<e&&e<=a?(h.style.cssText="",d==e?(prebackground=h.className,h.className="current",seltd=h):6==f?h.className="sat":
0==f&&(h.className="sun"),h.innerHTML=e,e++):(h.style.cssText="",h.innerHTML="")}}function getdate(c,d,a){d=is_ie?event.srcElement:d.target;"TD"==d.tagName&&""!=d.innerHTML&&(1==a?(seltd.className=prebackground,prebackground=d.className,d.className="current",seltd=d):(a=$("Year").value+"-"+$("Month").value+"-"+d.innerHTML,$(c).value=a,$(c).onblur&&$(c).onblur(),hideCalendar()))}
function getdate2(c){sDate=$("Year").value+"-"+$("Month").value+"-"+seltd.innerHTML+" "+$("Hour").value+":"+$("Minute").value;$(c).value=sDate;$(c).onblur&&$(c).onblur();hideCalendar()}function hideCalendar(){$("Calendar").style.visibility="hidden"}
function showcalendar(c,d){var a,e,b;b=$(c);b.id||(b.id="C"+b.name.hashCode());var g=b.id;e=new Date;e=e.getFullYear();today=b.value;today=isDate(today,d)?new getSelectDay(today,d):new getToday(d);if($("Calendar"))var f=$("Calendar");else f=elementBind("div","Calendar","","position:absolute; z-index:9999; visibility: hidden;"),document.body.appendChild(f);b=b.getBoundingClientRect();f.style.left=b.left+2+ietruebody().scrollLeft+"px";f.style.top=b.top+ietruebody().scrollTop+20+"px";f.style.visibility=
"visible";b='<iframe frameborder=\'0\' style=\'position:absolute;top:0;width:245px;height:200px;filter:Alpha(opacity=0);_filter:Alpha(opacity=0);opacity:.0;\'></iframe><div class="calendar-menu" style="position:absolute;margin-left:-2px;"><div class="date-select">';b+='<div class="calendar-top" style="border-bottom:0">';b+="<a class=\"closed\" title='\u5173\u95ed' onClick='javascript:hideCalendar()'>&times;</a>";b+="<select name='Year' id='Year' onChange='showDays()' style='font-family:Verdana; font-size:12px;margin-right:10px;'>";
for(a=e-35;a<e+10;a++)b+="<option value="+a+" "+(today.year==a?"Selected":"")+">"+a+"</option>";b+="</select>";b+="<select name='Month' id='Month' onChange='showDays()' style='font-family:Verdana; font-size:12px'>";for(a=0;a<months.length;a++)b+="<option value= "+(a+1)+" "+(today.month==a?"Selected":"")+">"+months[a]+"</option>";b+="</select>";b+="</div>";b+='<table id="Day" style="text-align:center" width="100%" cellspacing="1" cellpadding="3" align="center" border="0">';b+='<tr style="background:#f7fbff;">';
for(a=0;a<weeks.length;a++)b+="<th>"+weeks[a]+"</th>";b+="</tr>";for(e=0;6>e;e++){b+="<tr>";if(1==d)for(a=0;a<weeks.length;a++)b+="<td onClick='getdate(\""+g+'",event,"1")\' ondblclick=\'getdate2("'+g+"\")'><span>&nbsp;</span></td>";else for(a=0;a<weeks.length;a++)b+="<td onClick='getdate(\""+g+"\",event)'>&nbsp;</td>";b+="</tr>"}b+="</table>";1==d&&(b+='<div class="calendar-bot"><span style="margin-right:5px;"><input class="input" type="text" name="Hour" id="Hour" size="1" value="'+today.hour+'">\u70b9<input class="input" type="text" name="minute" id="Minute" size="1" value="'+
today.minute+'">\u5206</span><span class="btn2"><span><button type="button" name="submit" onClick=\'getdate2("'+g+"\")'>\u786e\u8ba4</button></span></span></div>");b+="</div>";f.innerHTML=b;showDays()}
function isDate(c,d){if(1==d){var a=/^(\d{4})(\-)(\d{1,2})(\-)(\d{1,2})(\s{1})(\d{1,2})(\:)(\d{1,2})/,a=c.match(a);if(null==a)return!1;var e=a[7],b=a[9];if(0>e||23<e||0>b||59<b)return!1}else if(a=/^(\d{4})(\-)(\d{1,2})(\-)(\d{1,2})/,a=c.match(a),null==a)return!1;e=a[3];b=a[5];a=a[1];return 1>e||12<e||1>b||31<b||(4==e||6==e||9==e||11==e)&&31==b||2==e&&(29<b||29==b&&(0!=a%4||0==a%100&&0!=a%400))?!1:!0}function trim(c){c=c.replace(/^\s+/,"");return c.replace(/\s+$/,"")}
function elementBind(c,d,a,e){c=document.createElement(c);d&&(c.id=d);"string"==typeof a&&(c.className=a);"string"==typeof e&&(c.style.cssText=e);return c}function ietruebody(){return document.compatMode&&"BackCompat"!=document.compatMode?document.documentElement:document.body};
