function getContentLength(){var a=-1;"object"==typeof tinyMCE&&(a=tinyMCE.get("editor_content").getContent().length);return a}function formSubmit(a){if("function"==typeof checkPostData&&!checkPostData(a))return!1;$("tab_imgattachlist")&&(a.appendChild($("tab_imgattachlist")),$("tab_imgattachlist").style.display="none",$("tab_imgattachlist").id="");return!0}
function toggleAttachTabs(a){for(var c=null,b=$("btn_"+a),d=b.parentNode.getElementsByTagName("LI"),e=0;e<d.length;e++)"btn_"==d[e].id.substr(0,4)&&d[e].id!=b.id&&(c="tab_"+d[e].id.substr(4),$(c)&&(d[e].className="",$(c).style.display="none"));b.className="current";$("tab_"+a).style.display=""}function toggleTabstrip(a){toggleAttachTabs(a)}
function showAttachWindow(a,c){if(phpcom.isIE6){var b=document.createElement("iframe");b.id="fbox_uploadattach_iframe";b.className="frmie6";b.style.display="block";b.style.border="none";b.style.position="absolute";b.style.zIndex=-1;b.style.top="0";b.style.left="0";b.style.backgroundColor="#ff0";b.style.filter="progid:DXImageTransform.Microsoft.Alpha(opacity=0)";b.style.opacity=0;$("fbox_uploadattach")&&$("fbox_uploadattach").appendChild(b)}menu.show({cache:"1",menuid:"fbox_uploadattach",type:"window",
pos:"00",zindex:menu.zindex.window,duration:3,drag:"fdrag_uploadattach"});phpcom.endEvent()}function hideAttachWindow(a){$("fbox_"+a)&&($("fbox_"+a).style.display="none")}function SWFUploadHandler(a,c){2==a&&("image"==c?updateImageList():updateAttachList())}function updateAttachList(a,c,b){var d=$("channelid").value;ajaxget("apps/ajax.php?action=attachlist&type=attach&chanid="+d+(a?c?"&aids="+c:"":"&posttime="+$("posttime").value)+(b?"&uid="+b:""),"attachlist");toggleAttachTabs("attachlist")}
function updateImageList(a,c,b){var d=$("channelid").value;ajaxget("apps/ajax.php?action=attachlist&type=image&chanid="+d+(a?c?"&aids="+c:"":"&posttime="+$("posttime").value)+(b?"&uid="+b:""),"imgattachlist");try{toggleAttachTabs("imgattachlist")}catch(e){}}
function insertAttachimgTag(a){var c=$("uploadimage_"+a);c?tinyMCE.execCommand("mceInsertContent",!1,'<img width="300" src="'+c.src.replace(/&thumb=yes/ig,"")+'" id="editor_attachimg_'+a+'" style="max-width:600px" />'):tinyMCE.execCommand("mceInsertContent",!1,"[attachimg]"+a+"[/attachimg]");return!1}function setThreadImage(a){$("threadimageaid")&&($("threadimageaid").value=a,showMessage("\u8bbe\u7f6e\u9884\u89c8\u7f29\u7565\u56fe\u6210\u529f!"))}
function deleteImage(a,c,b){if($("imagebox_"+a)){$("imagebox_"+a).className="deleted";$("uploadimage_"+a).onclick=null;$("imagedesc_"+a).disabled=!0;$("imagesort_"+a)&&($("imagesort_"+a).disabled=!0);for(var d=$("imagebox_"+a).getElementsByTagName("A"),e=0;e<d.length;e++)d[e].onclick="return false",d[e].href="#";d=$("imagebox_"+a).getElementsByTagName("INPUT");for(e=0;e<d.length;e++)d[e].onclick=null,d[e].disabled=!0}ajaxget("apps/misc.php?action=delattach&chanid="+b+"&aid="+a+"&key="+c)}
function updateAttachWindow(a,c,b){showWindow("apps/ajax.php?action=upload&type="+a+"&aid="+c+"&chanid="+b,"upload")}function loadUploadWindow(){var a=$("uploadattachframe").contentWindow.document.body.innerHTML;""!=a&&(a=(new Function("return "+a))(),"image"==a.type&&(a=$("uploadimage_"+a.attachid))&&(a.src=a.src+"&t="+(new Date).getTime()),setTimeout(function(){hideWindow("upload")},200))}
var UPLOAD_STATUS={QUEUE_LIMIT_EXCEEDED:-100,UPLOAD_STOPPED:-110,HTTP_ERROR:-1,MAX_LIMIT_EXCEEDED:1,EXCEEDS_SIZE_LIMIT:2,FILE_ONLY_PARTIALLY:3,FILE_NOT_FOUND:4,INVALID_FILETYPE:5,INVALID_IMAGE_MIME:6,SERVER_IO_ERROR:7,FILE_DENIED:8,FUNCTION_CLOSED:9,PERMISSION_DENIED:10},fileQueue={count:0,num:0,start:0};
function UploadQueue(a,c){this.fileQueueID=a.id;this.opacity=100;this.height=0;if(this.fileQueueWrapper=document.getElementById(this.fileQueueID))this.fileQueueElement=this.fileQueueWrapper.firstChild,this.reset();else{this.fileQueueWrapper=document.createElement("div");this.fileQueueWrapper.className="progressWrapper";this.fileQueueWrapper.id=this.fileQueueID;this.fileQueueElement=document.createElement("div");this.fileQueueElement.className="progressContainer";var b=document.createElement("a");
b.className="progressCancel";b.href="#";b.name=a.formid;b.style.visibility="hidden";b.appendChild(document.createTextNode(" "));var d=document.createElement("div");d.className="progressName";d.appendChild(document.createTextNode(a.name));var e=document.createElement("div");e.className="progressBarInProgress";var f=document.createElement("div");f.className="progressBarStatus";f.innerHTML="&nbsp;";this.fileQueueElement.appendChild(e);this.fileQueueElement.appendChild(b);this.fileQueueElement.appendChild(d);
this.fileQueueElement.appendChild(f);this.fileQueueWrapper.appendChild(this.fileQueueElement);document.getElementById(c).appendChild(this.fileQueueWrapper)}this.height=this.fileQueueWrapper.offsetHeight;this.setTimer(null)}UploadQueue.prototype.setTimer=function(a){this.fileQueueElement.FUQ_TIMER=a};UploadQueue.prototype.getTimer=function(a){return this.fileQueueElement.FUQ_TIMER||null};
UploadQueue.prototype.reset=function(){this.fileQueueElement.className="progressContainer";this.fileQueueElement.childNodes[3].innerHTML="&nbsp;";this.fileQueueElement.childNodes[3].className="progressBarStatus";this.fileQueueElement.childNodes[0].className="progressBarInProgress";this.fileQueueElement.childNodes[0].style.width="0%";this.appear()};
UploadQueue.prototype.setProgress=function(a){this.fileQueueElement.className="progressContainer green";this.fileQueueElement.childNodes[0].className="progressBarInProgress";this.fileQueueElement.childNodes[0].style.width=a+"%";this.appear()};
UploadQueue.prototype.setComplete=function(){this.fileQueueElement.className="progressContainer blue";this.fileQueueElement.childNodes[0].className="progressBarComplete";this.fileQueueElement.childNodes[0].style.width="100%";var a=this;this.setTimer(setTimeout(function(){a.disappear()},1E4))};
UploadQueue.prototype.setError=function(){this.fileQueueElement.className="progressContainer red";this.fileQueueElement.childNodes[0].className="progressBarError";this.fileQueueElement.childNodes[0].style.width="";var a=this;this.setTimer(setTimeout(function(){a.disappear()},5E3))};
UploadQueue.prototype.setCancelled=function(){this.fileQueueElement.className="progressContainer";this.fileQueueElement.childNodes[0].className="progressBarError";this.fileQueueElement.childNodes[0].style.width="";var a=this;this.setTimer(setTimeout(function(){a.disappear()},2E3))};UploadQueue.prototype.setStatus=function(a){this.fileQueueElement.childNodes[3].innerHTML=a};
UploadQueue.prototype.toggleCancel=function(a){this.fileQueueElement.childNodes[1].style.visibility=a?"visible":"hidden";var c=this,b=this.fileQueueElement.childNodes[1];this.fileQueueElement.childNodes[1].onclick=function(){c.setStatus("\u53d6\u6d88\u4e0a\u4f20......");setTimeout(function(){c.fileQueueWrapper.parentNode.removeChild(c.fileQueueWrapper);$(b.name)&&$(b.name).parentNode.parentNode.removeChild($(b.name).parentNode)},1E3);return!1}};
UploadQueue.prototype.appear=function(){null!==this.getTimer()&&(clearTimeout(this.getTimer()),this.setTimer(null));if(this.fileQueueWrapper.filters)try{this.fileQueueWrapper.filters.item("DXImageTransform.Microsoft.Alpha").opacity=100}catch(a){this.fileQueueWrapper.style.filter="progid:DXImageTransform.Microsoft.Alpha(opacity=100)"}else this.fileQueueWrapper.style.opacity=1;this.fileQueueWrapper.style.height="";this.height=this.fileQueueWrapper.offsetHeight;this.opacity=100;this.fileQueueWrapper.style.display=
""};
UploadQueue.prototype.disappear=function(){if(0<this.opacity)if(this.opacity-=15,0>this.opacity&&(this.opacity=0),this.fileQueueWrapper.filters)try{this.fileQueueWrapper.filters.item("DXImageTransform.Microsoft.Alpha").opacity=this.opacity}catch(a){this.fileQueueWrapper.style.filter="progid:DXImageTransform.Microsoft.Alpha(opacity="+this.opacity+")"}else this.fileQueueWrapper.style.opacity=this.opacity/100;0<this.height&&(this.height-=4,0>this.height&&(this.height=0),this.fileQueueWrapper.style.height=this.height+
"px");if(0<this.height||0<this.opacity){var c=this;this.setTimer(setTimeout(function(){c.disappear()},30))}else this.fileQueueWrapper.style.display="none",this.setTimer(null)};
function insertAttach(a,c){try{if(""!=a.value){c=c?c:"attach";var b=a.value.substr(a.value.replace(/\\/g,"/").lastIndexOf("/")+1),d={};d.id=c+"UploadQueueWrapper_"+a.index;d.name=b;d.index=a.index;d.type=c;d.formid=a.formid;d.ext=-1==b.lastIndexOf(".")?"":b.substr(b.lastIndexOf(".")+1).toLowerCase();fileQueue[a.index]=d;var e=new UploadQueue(d,c+"UploadQueue");e.setStatus("\u7b49\u5f85\u4e0a\u4f20......");e.toggleCancel(!0);fileQueue.count++;a.style.display="none";$(a.formid)&&$(a.formid).setAttribute("queueid",
a.index);$(c+"UploadBtn").disabled=!1;appendAttachQueue(c)}}catch(f){}}
function appendAttachQueue(a){a=a?a:"attach";var c=fileQueue.count,b=a+"uploadform_"+c,d=$(a+"UploadForm").firstChild.cloneNode(!0),e=d.getElementsByTagName("INPUT"),f;for(f in e)"Filedata"==e[f].name?(e[f].id=a+"Filedata_"+c,e[f].onchange=function(b){insertAttach(this,a)},e[f].unselectable="on",e[f].index=c,e[f].formid=b):"queueid"==e[f].name&&(e[f].value=c);e=d.getElementsByTagName("form");e[0].name=e[0].id=a+"uploadform_"+c;$(a+"UploadFile").appendChild(d)}
function startUploadAttach(a,c){var b=$(a+"UploadFile");if(-1==fileQueue.start)return showMessage("\u60a8\u6ca1\u6709\u4e0a\u4f20\u9644\u4ef6\u7684\u6743\u9650\u6216\u6b64\u529f\u80fd\u5df2\u88ab\u7ba1\u7406\u5458\u7981\u6b62"),!1;if("object"==typeof c){var d=fileQueue[c.queueid];d.size=c.size;if(0==c.status)fileQueue.num++,$(a+"UploadStatus").innerHTML=fileQueue.num+" \u4e2a\u6587\u4ef6\u5df2\u4e0a\u4f20.",uploadAttachSuccess(d);else{if(10==c.status||9==c.status)return fileQueue.num=0,fileQueue.start=
-1,uploadAttachError(d,c.status),showMessage("\u60a8\u6ca1\u6709\u4e0a\u4f20\u9644\u4ef6\u7684\u6743\u9650\u6216\u6b64\u529f\u80fd\u5df2\u88ab\u7ba1\u7406\u5458\u7981\u6b62"),!1;uploadAttachError(d,c.status)}}else fileQueue.start=0;for(var d=b.getElementsByTagName("form"),e=0,f=d.length-1;e<f;e++)if(0<=d[e].getAttribute("queueid")){f=fileQueue[d[e].getAttribute("queueid")];uploadAttachProgress(f,20,100);fileQueue.start++;d[e].submit();$(a+"UploadBtn").disabled=!0;b.removeChild(b.firstChild);return}0==
fileQueue.start?showMessage("\u4e0a\u4f20\u5217\u961f\u4e3a\u7a7a"):(setTimeout(function(){updateImageList()},1E3),fileQueue.num=0);return!0}function uploadCallback(){var a=$("uploadframe").contentWindow.document.body.innerHTML;if(""!=a){var c=(new Function("return "+a))();setTimeout(function(){startUploadAttach(c.type,c)},200)}}
function uploadAttachError(a,c){try{var b=new UploadQueue(a,a.type+"UploadQueue");b.setError();b.toggleCancel(!1);switch(c){case UPLOAD_STATUS.HTTP_ERROR:b.setStatus("\u4e0a\u4f20\u9519\u8bef.");break;case UPLOAD_STATUS.EXCEEDS_SIZE_LIMIT:case UPLOAD_STATUS.MAX_LIMIT_EXCEEDED:b.setStatus("\u4e0a\u4f20\u5931\u8d25\uff01\u4e0a\u4f20\u6587\u4ef6\u8d85\u51fa\u6700\u5927\u4e0a\u4f20\u9650\u5236.");break;case UPLOAD_STATUS.FILE_ONLY_PARTIALLY:case UPLOAD_STATUS.FILE_NOT_FOUND:b.setStatus("\u4e0a\u4f20\u5931\u8d25\uff01\u6ca1\u6709\u6587\u4ef6\u88ab\u4e0a\u4f20.");
break;case UPLOAD_STATUS.INVALID_FILETYPE:b.setStatus("\u65e0\u6548\u7684\u6587\u4ef6\u7c7b\u578b.");break;case UPLOAD_STATUS.INVALID_IMAGE_MIME:b.setStatus("\u65e0\u6548\u7684\u56fe\u7247\u7c7b\u578b.");break;case UPLOAD_STATUS.SERVER_IO_ERROR:b.setStatus("\u670d\u52a1\u5668 (IO) \u9519\u8bef");break;case UPLOAD_STATUS.UPLOAD_FAILED:b.setStatus("\u4e0a\u4f20\u5931\u8d25.");break;case UPLOAD_STATUS.FUNCTION_CLOSED:b.setStatus("\u4e0a\u4f20\u529f\u80fd\u88ab\u5173\u95ed.");break;case UPLOAD_STATUS.PERMISSION_DENIED:b.setStatus("\u60a8\u6ca1\u6709\u4e0a\u4f20\u9644\u4ef6\u7684\u6743\u9650\u6216\u6b64\u529f\u80fd\u5df2\u88ab\u7ba1\u7406\u5458\u7981\u6b62.");
break;case UPLOAD_STATUS.UPLOAD_STOPPED:b.setStatus("\u4e0a\u4f20\u7ec8\u6b62");break;default:b.setStatus("\u65e0\u6cd5\u5904\u7406\u7684\u9519\u8bef: "+c)}}catch(d){}}function uploadAttachProgress(a){try{var c=new UploadQueue(a,a.type+"UploadQueue");c.setProgress(0);c.setStatus("\u6b63\u5728\u4e0a\u4f20\u9644\u4ef6,\u8bf7\u7a0d\u5019......")}catch(b){}}
function uploadAttachSuccess(a){try{var c=new UploadQueue(a,a.type+"UploadQueue"),b=formatBytes(a.size);c.setComplete();c.setStatus('<font color="red">'+b+"</font> \u9644\u4ef6\u4e0a\u4f20\u6210\u529f.");c.toggleCancel(!1)}catch(d){}};
