var tipInfo=tmpItem=[],lastUserName="",lastEmail="",lastInviteCode="";
function addFormEvents(b,a){for(var c=0,d=$(b).getElementsByTagName("input"),e=0;e<d.length;e++)if("text"==d[e].type||"password"==d[e].type)d[e].onfocus=function(){showInputTip(!this.id?this.name:this.id)},d[e].id&&$("tip_"+d[e].id)&&(tmpItem[c]=e,tipInfo[d[e].id]=$("tip_"+d[e].id).innerHTML,c++);c&&(d[tmpItem[0]].onblur=function(){checkUserName(d[tmpItem[0]].id)},d[tmpItem[0]].focus(),d[tmpItem[1]].onblur=function(){""==d[tmpItem[1]].value.trim()?showerrmsg(d[tmpItem[1]].id,"\u8bf7\u586b\u5199\u5bc6\u7801"):
showerrmsg(d[tmpItem[1]].id,"succeed");checkPassWord(d[tmpItem[1]].id,d[tmpItem[2]].id)},d[tmpItem[2]].onblur=function(){""==d[tmpItem[2]].value.trim()&&showerrmsg(d[tmpItem[2]].id,"\u8bf7\u518d\u6b21\u8f93\u5165\u5bc6\u7801");checkPassWord(d[tmpItem[1]].id,d[tmpItem[2]].id)},d[tmpItem[3]].onblur=function(){""==d[tmpItem[3]].value.trim()&&showerrmsg(d[tmpItem[3]].id,"\u8bf7\u8f93\u5165\u90ae\u7bb1\u5730\u5740");checkEmail(d[tmpItem[3]].id)},$("tip_invitecode")&&$("invitecode")&&($("invitecode").onblur=
function(){""==$("invitecode").value.trim()?showerrmsg("invitecode","\u672c\u7ad9\u5df2\u5f00\u542f\u9080\u8bf7\u6ce8\u518c\uff0c\u8bf7\u586b\u5199\u9080\u8bf7\u7801"):checkInviteCode("invitecode")}))}function showInputTip(b){for(var a=$("formregister").getElementsByTagName("i"),c=0;c<a.length;c++)"tipmsg"==a[c].className&&(a[c].style.display="none");$("tip_"+b)&&($("tip_"+b).className="tipmsg",$("tip_"+b).style.display="",$("tip_"+b).innerHTML=tipInfo[b])}
function showerrmsg(b,a){$(b)&&(showInputTip(),a=!a?"":a,$("tip_"+b)&&("succeed"==a&&(a=""),$("tip_"+b).style.display="",$("tip_"+b).innerHTML=a,$("tip_"+b).className=!a?"sucmsg":"errmsg"))}function checksubmit(b){b=b.getElementsByTagName("i");for(var a=0;a<b.length;a++)if("tipmsg"==b[a].className||"sucmsg"==b[a].className||"chksuc"==b[a].className)b[a].innerHTML="";ajaxpost("formregister",null,null,function(a){"succeed"!=a&&showMessage(a)});return!1}
function checkUserName(b){showerrmsg(b);var a=$(b).value.trim();if(!("errmsg"==$("tip_"+b).className&&(""==a||a==lastUserName)))if(lastUserName=a,a.match(/<|>|#|%|\/|\\|\||\*|\$|,|;|'|"/ig))showerrmsg(b,"\u7528\u6237\u540d\u5305\u542b\u654f\u611f\u5b57\u7b26\u201c<>#%/|*$;\u201d");else{var c=a.replace(/[^\x00-\xff]/g,"**").length;c<usernameminlen||c>usernamemaxlen?showerrmsg(b,c<usernameminlen?"\u7528\u6237\u540d\u5c0f\u4e8e "+usernameminlen+" \u4e2a\u5b57\u7b26":"\u7528\u6237\u540d\u8d85\u8fc7 "+
usernamemaxlen+" \u4e2a\u5b57\u7b26"):(a="apps/misc.php?action=ajax&inajax=1&token=register&check=username&username="+(phpcom.isIE&&"utf-8"==document.charset?encodeURIComponent(a):a),c=ajaxObject(),c.setWaiting("tip_"+b),c.get(a,function(a){showerrmsg(b,a)}))}}function checkPassWord(b,a){if($(b).value||$(a).value)showerrmsg(a),$(b).value!=$(a).value?showerrmsg(a,"\u4e24\u6b21\u8f93\u5165\u7684\u5bc6\u7801\u4e0d\u4e00\u81f4"):showerrmsg(a,"succeed")}
function checkEmail(b){showerrmsg(b);var a=$(b).value.trim();if(!("errmsg"==$("tip_"+b).className&&(""==a||a==lastEmail)))if(lastEmail=a,/^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/.test(a))if(a.match(/<|>|#|%|\/|\\|\||\*|\$|,|;|'|"/ig))showerrmsg(b,"Email \u5305\u542b\u654f\u611f\u5b57\u7b26\u201c<>#%/|*$;\u201d");else{var a="apps/misc.php?action=ajax&inajax=1&token=register&check=email&email="+a,c=ajaxObject();c.setWaiting("tip_"+b);c.get(a,function(a){showerrmsg(b,a)})}else showerrmsg(b,"\u65e0\u6548\u7684 Email \u5730\u5740")}
function checkInviteCode(b){showerrmsg(b);var a=$(b).value.trim();if(!("errmsg"==$("tip_"+b).className&&(""==a||a==lastInviteCode)))if(lastInviteCode=a,a.match(/<|>|#|%|\/|\\|\||\*|\$|,|;|'|"/ig))showerrmsg(b,"\u9080\u8bf7\u7801\u5305\u542b\u654f\u611f\u5b57\u7b26\u201c<>#%/|*$;\u201d");else{var a="apps/misc.php?action=ajax&inajax=1&token=register&check=invitecode&invitecode="+a,c=ajaxObject();c.setWaiting("tip_"+b);c.get(a,function(a){showerrmsg(b,a)})}}
function checkVerifyCode(b){var a=$(b).value.trim();if(""!=a){var c=$("checkCaptcha");c.style.display="";if(4!=a.length)c.className="chkerr";else{var a="apps/misc.php?action=captcha&inajax=1&token=captcha&check=yes&verifycode="+(phpcom.isIE&&"utf-8"==document.charset?encodeURIComponent(a):a),d=ajaxObject();d.setWaiting(b);d.get(a,function(a){"succeed"==a.substr(0,7)?c.className="chksuc":c.className="chkerr"})}}}
function checkQuestionAnswer(b){var a=$(b).value.trim();if(""!=a){var a="apps/misc.php?action=questions&inajax=1&token=questions&check=yes&answer="+(phpcom.isIE&&"utf-8"==document.charset?encodeURIComponent(a):a),c=ajaxObject();c.setWaiting(b);c.get(a,function(a){var b=$("checkQuestions");b.style.display="";"succeed"==a.substr(0,7)?b.className="chksuc":b.className="chkerr"})}}function showTerms(b){showWindow("apps/ajax.php?action=terms","readterms","get",1,b);$("registerterms").checked=!0}
function checkedTerms(){$("registerterms").checked=!0;hideMenu("show_window_readterms","window")};
